const Languages = {
  en: {
    "Submit": "Submit",
    "Empty List": "Empty List",
    "What are you looking for?": "What are you looking for?",
    "See All": "See All",
    "Browser By Category": "Browser By Category",
    "Brands": "Brands",
    "Free Shipping": "Free Shipping",
    "Quantity": "Quantity",
    "Total": "Total",
    "Checkout": "Checkout",
    "My Orders": "My Orders",
    "My WishList": "My WishList",
    "Yours": "Yours",
    "My Address Book": "My Address Book",
    "New Feeds": "New Feeds",
    "Add to Cart": "Add to Cart",
    "Results": "Results",
    "Result": "Result",
    "Change Language": "Change Language",
    "Rate App": "Rate App",
    "Share App": "Share App",
    "Can not connect to server": "Can not connect to server.",
    "Sponsored": "Sponsored",
    "Category": "Category",
    "Price Range": "Price Range",
    "Brand": "Brand",
    "Feedback": "Feedback",
    "Email": "Email",
    "Password": "Password",
    "Sign In": "Sign In",
    "Sign Up": "Sign Up",
    "Do you have account with Hubay?": "Do you have account with Hubay?",
    "First Name": "First Name",
    "Last Name": "Last Name",
    "Done ! Thank you for your order.": "Done ! Thank you for your order.",
    "Telephone": "Telephone",
    "Street": "Street",
    "City": "City",
    "Postcode": "Postcode",
    "Choose Country": "Choose Country",
    "Shipping Methods": "Shipping Methods",
    "Please choose shipping method": "Please choose shipping method.",
    "Please input all fields": "Please input all fields",
    "Payment Methods": "Payment Methods",
    "Sign Out": "Sign Out",
    "Add Address": "Add Address",
    "Choose Region": "Choose Region",
    "Status": "Status",
    "Created": "Created",
    "Code": "Code",
    "Email or password is incorrect": "Email or password is incorrect.",
    "Don't have any shipping methods at your address":
    "Don't have any shipping methods at your address",
    "Top Deals": "Top Deals",
    "Sort by": "Sort by",
    "Filter": "Filter",
    "Clear": "Clear",
    "Apply": "Apply",
    "None": "None",
    "Tags": "Tags",
    "Attributes": "Attributes",
    "Read more": "Read more",
    "Availability": "Availability",
    "Out of stock": "Out of stock",
    "in stock": "in stock",
    "Vendor Information": "Vendor Information",
    "Name": "Name",
    "Store name": "Store name",
    "Email": "Email",
    "Rating": "Rating",
    "Specification": "Specification",
    "Categories": "Categories",
    "Reviews": "Reviews",
    "Products for vendor": "Products for vendor",
    "Login With Facebook": "Login With Facebook",
    "Welcome": "Welcome",
    "Remember me": "Remember me",
    "By Books for Gifting": "Buy Books for Gifting",
    "Send Gift": "Send Gift",
    "Track Package": "Track Package",
    "Resend Invite": "Resend Invite",
    "Downlines": "Downlines: ",
    "Books Gifted": "Books Gifted: ",
    "Gift Accepted": "Gift Accepted",
    "Invite Declined": "Invite Declined",
    "Invite Accepted": "Invite Accepted",
    "Seva Points": "Seva Points",
    "Level": "Level",
    "DownlinesCol":"Downlines",
    "Books Gifted Col":"Books Gifted"
  },
  ar: {
    "Submit": "ارسال",
    "Empty List": "القائمة فارغة",
    "What are you looking for?": "عن ماذا تريد أن تبحث",
    "See All": "مشاهدة الجميع",
    "Browser By Category": "تصفح القائمة",
    "Brands": "علامة تجارية",
    "Free Shipping": "شحن مجاني",
    "Quantity": "الكمية",
    "Total": "المجموع",
    "Checkout": "الدفع",
    "My Orders": "طلباتي",
    "My WishList": "مفضلتي",
    "Yours": "خاصة لك",
    "My Address Book": "عنواني",
    "New Feeds": "الجديد",
    "Add to Cart": "اضف الى سلتي",
    "Results": "النتائج",
    "Result": "النتيجة",
    "Change Language": "تغيير اللغة",
    "Rate App": "قيم البرنامج",
    "Share App": "ارسل التطبيق ",
    "Can not connect to server": "لا يمكن الاتصال بالخادم",
    "Sponsored": "برعاية",
    "Category": "القوائم",
    "Price Range": "السعر بين",
    "Brand": "العلامة التجارية",
    "Feedback": "الرد",
    "Email": "البريد الالكتروني",
    "Password": "الرمز السري",
    "Sign In": "تسجيل الدخول",
    "Sign Up": "التسجيل",
    "Do you have account with Hubay?": "هل يوجد عندك حساب معنا ؟",
    "First Name": "الاسم الأول",
    "Last Name": "الاسم اأخير",
    "Done ! Thank you for your order.": "شكرا لك على الطلب",
    "Telephone": "الهاتف",
    "Street": "الشارع",
    "City": "المدينة",
    "Postcode": "الرمز البريدي",
    "Choose Country": "اختر الدولة",
    "Shipping Methods": "طريقة التوصيل",
    "Please choose shipping method": "من فضلك اختر طريقة التوصيل",
    "Please input all fields": "يرجي ملئ كافة الحقول",
    "Payment Methods": "طريقة الدفع",
    "Sign Out": "تسجيل الخروج",
    "Add Address": "اضف عنوان",
    "Choose Region": "اختر المنطقة",
    "Status": "الحالة",
    "Created": "تم الانشاء",
    "Code": "الكود",
    "Email or password is incorrect": "البريد الالكتروني او رقم المرور خطأ",
    "Don't have any shipping methods at your address":
      "لا يوجد اي عنوان في قائمة العناوين",
    "Top Deals": "افضل العروض",
    "Sort by": "رتب حسب",
    "Filter": "فلتر",
    "Clear": "مسح",
    "Apply": "طبق",
    "None": "لايوجد",
    "Tags": "اختصار",
    "Attributes": "خصائص",
    "Read more": "اقرا المزيد",
    "Availability": "متوفر",
    "Out of stock": "غير متوفر",
    "in stock": "يوجد مخزون",
    "Vendor Information": "عن البائع",
    "Name": "الاسم",
    "Store name": "اسم المحل",
    "Email": "البريد الالكتروني",
    "Rating": "التقييم",
    "Specification": "الميزات",
    "Categories": "الاقسام",
    "Reviews": "التقيمات",
    "Products for vendor": "منتجات هذا البائع",
    "Login With Facebook": "الدخول عبر الفيسبوك",
    "Welcome": "اهلا وسهلا",
    "Remember me": "تذكرني",
    "By Books for Gifting": "Buy Books for Gifting",
    "Send Gift": "Send Gift",
    "Track Package": "Track Package",
    "Resend Invite": "Resend Invite",
    "Downlines": "Downlines: ",
    "Books Gifted": "Books Gifted: ",
    "Gift Accepted": "Gift Accepted",
    "Invite Declined": "Invite Declined",
    "Invite Accepted": "Invite Accepted",
    "Seva Points": "Seva Points",
    "Level": "Level",
    "DownlinesCol":"Downlines",
    "Books Gifted Col":"Books Gifted"
  }
};

export default Languages;
